### ISSUE TITLE
how can i get weight model file ?

### ISSUE THREAD

**Issue by foolfrog** [auroua/tf_rfcn#6]
when i trained rfcn net with command:
python tools/trainval_net_rfcn.py --cfg=experiments/cfgs/res101_rfcn.yml 
I got errors:
>......
> Loading initial model weights from None
> Expected binary or unicode string, got None
> Traceback (most recent call last):
>   File "tools/trainval_net_rfcn.py", line 125, in <module>
>     max_iters=args.max_iters)
>   File "/home/aigo/deeplearning/tf_rfcn/lib/model/train_val_rfcn_iteration4.py", line 528, in train_net
>     sw.train_model(sess, max_iters)
>   File "/home/aigo/deeplearning/tf_rfcn/lib/model/train_val_rfcn_iteration4.py", line 177, in train_model
>     variables_to_restore_rpn, variables_to_restore_rfcn = self.net.get_variables_to_restore(variables, var_keep_dic)
>   File "/home/aigo/deeplearning/tf_rfcn/lib/tf_nets/resnet_v1_rfcn_hole_iterator4.py", line 365, in get_variables_to_restore
>     if v.name.split(':')[0].replace('rpn_network/', '') in var_keep_dic:
> TypeError: argument of type 'NoneType' is not iterable

it may be caused by i have not given a weight file .
what should i do? thanks!

**Comment by foolfrog** [comment]
i download model B and use --weight=res101_faster_rcnn_iter_110000.ckpt, fixed! thanks
